apiVersion: v1
kind: Service
metadata:
  name: service-api
  labels:
    app: weaponry-api
    tier: database
spec:
  type: NodePort 
  ports:
    - port: 8000
      targetPort: 3306
      Nodeport: 30080
  selector:
    app: weaponry-api