apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql
spec:
  selector:
    matchLabels:
      app: weaponry-sql
  serviceName: service-sql
  replicas: 2
  template:
    metadata:
      labels:
        app: weaponry-sql
    spec:
      containers:                                     
      - name: sql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword
        - name: MYSQL_DATABASE
          value: weapons
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
        name: sql-volume
  volumeClaimTemplates:
  - metadata:
      name: sql-volume
    spec:
      storageClassName: "sql-db"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi